#include "stm32h743xx.h"

void GPIO_Init(void){
  RCC->AHB4ENR |= RCC_AHB4ENR_GPIOAEN;

  // --- SPI1: PA5=SCK, PA6=MISO, PA7=MOSI ---
  GPIOA->MODER &= ~(GPIO_MODER_MODE5 | GPIO_MODER_MODE6 | GPIO_MODER_MODE7);
  GPIOA->MODER |=  (GPIO_MODER_MODE5_1 | GPIO_MODER_MODE6_1 | GPIO_MODER_MODE7_1);

  GPIOA->AFR[0] &= ~(GPIO_AFRL_AFSEL5 | GPIO_AFRL_AFSEL6 | GPIO_AFRL_AFSEL7);
  GPIOA->AFR[0] |=  (5U << GPIO_AFRL_AFSEL5_Pos) |
                     (5U << GPIO_AFRL_AFSEL6_Pos) |
                     (5U << GPIO_AFRL_AFSEL7_Pos);

  GPIOA->OTYPER  &= ~(GPIO_OTYPER_OT5 | GPIO_OTYPER_OT6 | GPIO_OTYPER_OT7);
  GPIOA->PUPDR   &= ~(GPIO_PUPDR_PUPD5 | GPIO_PUPDR_PUPD6 | GPIO_PUPDR_PUPD7);
  GPIOA->OSPEEDR |=  (GPIO_OSPEEDR_OSPEED5 | GPIO_OSPEEDR_OSPEED6 | GPIO_OSPEEDR_OSPEED7);

  // --- CS: PA4 as push-pull output, idle HIGH (deselected) ---
  GPIOA->MODER &= ~GPIO_MODER_MODE4;
  GPIOA->MODER |=  GPIO_MODER_MODE4_0;      // 01 = general-purpose output
  GPIOA->OTYPER &= ~GPIO_OTYPER_OT4;        // push-pull
  GPIOA->PUPDR  &= ~GPIO_PUPDR_PUPD4;
  GPIOA->OSPEEDR |= GPIO_OSPEEDR_OSPEED4;
  GPIOA->BSRR = GPIO_BSRR_BS4;              // start deselected
}